<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>grainwallet-dashboard</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NBomber" Version="6.4.0" />
    <PackageReference Include="MessagePack" Version="2.5.301" />
  </ItemGroup>

</Project>
