<Project Sdk="Aspire.AppHost.Sdk/13.3.2">

  <ItemGroup>
    <ProjectReference Include="..\PlayerWallet.Api\PlayerWallet.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Kafka" Version="13.3.3" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.3.3" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>adcb3f11-0806-4adc-8db0-701dee5e4350</UserSecretsId>
  </PropertyGroup>

</Project>
