<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
    <PackageReference Include="Microsoft.Orleans.Server" Version="10.1.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.14.14" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PlayerWallet.Contracts\PlayerWallet.Contracts.csproj" />
    <ProjectReference Include="..\PlayerWallet.Grains\PlayerWallet.Grains.csproj" />
    <ProjectReference Include="..\PlayerWallet.ServiceDefaults\PlayerWallet.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
